apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dso202-assignment-01
  labels:
    app: task-tracker
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-tracker
      tier: backend
  template:
    metadata:
      labels:
        app: task-tracker
        tier: backend
    spec:
      serviceAccountName: backend-sa
      containers:
        - name: api
          image: pdolker/dso202-backend:1.0   # TEMP: my amd64 build
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef: {name: app-config, key: DB_HOST}
            - name: DB_PORT
              valueFrom:
                configMapKeyRef: {name: app-config, key: DB_PORT}
            - name: DB_NAME
              valueFrom:
                configMapKeyRef: {name: app-config, key: DB_NAME}
            - name: APP_PORT
              valueFrom:
                configMapKeyRef: {name: app-config, key: APP_PORT}
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef: {name: app-config, key: CORS_ORIGIN}
            - name: DB_USER
              valueFrom:
                secretKeyRef: {name: db-credentials, key: DB_USER}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef: {name: db-credentials, key: DB_PASSWORD}
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi