apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: dso202-assignment-01
  labels:
    app: task-tracker
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: task-tracker
    tier: backend
  ports:
    - port: 8080
      targetPort: 8080
