apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: dso202-assignment-01
  labels:
    app: task-tracker
type: Opaque
data:
  DB_USER: dGFza3VzZXI=
  DB_PASSWORD: VGFza1Bhc3MjMjAyNg==
  POSTGRES_USER: dGFza3VzZXI=
  POSTGRES_PASSWORD: VGFza1Bhc3MjMjAyNg==
