apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: dso202-assignment-01
  labels:
    app: task-tracker
    tier: database
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: task-tracker
      tier: database
  template:
    metadata:
      labels:
        app: task-tracker
        tier: database
    spec:
      containers:
        - name: postgres
          image: pdolker/dso202-db:1.0   # TEMP: my amd64 build
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef: {name: app-config, key: POSTGRES_DB}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef: {name: db-credentials, key: POSTGRES_USER}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef: {name: db-credentials, key: POSTGRES_PASSWORD}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-pvc
