apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: dso202-assignment-01
  labels:
    app: task-tracker
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
